tasks:
  - init: |
      nvm install $(jq -r .engines.node package.json) &&
      curl https://install.meteor.com/ | sh &&
      export PATH="$PATH:$HOME/.meteor" &&
      yarn &&
      export ROOT_URL=$(gp url 3000)
    command: yarn build && yarn dev

ports:
  - port: 3000
    visibility: public
    onOpen: open-preview 

github:
  prebuilds:
    master: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - esbenp.prettier-vscode       